### PR TITLE
[Response Datastore] Build fail issue fix

### PR DESCRIPTION
**Pull request by aswinijena100**
[Response Datastore] Build fail issue #2354   & #2259   fix

### CODE REVIEW

**Review by jkrogers18 — COMMENTED** [review]
I just tested this and I'm still getting test failures. Logs [here](https://drive.google.com/file/d/12YdvhBFPHD5w0FyDJ7ONd_VPG4BqeRRe/view?usp=sharing).

**Comment by dhanyak-btc** [comment]
@jkrogers18 I assume you have run the tests on `develop-response-server-build-fail-issue-fix` branch, not from `develop `branch.

@aswinijena100 port `8080 `is default in tomcat so this may cause issue if any application running on this port, please replace `8080 `with `54804 `for wiremock server.

**Comment by jkrogers18** [comment]
> @jkrogers18 I assume you have run the tests on `develop-response-server-build-fail-issue-fix` branch, not from `develop `branch. Please confirm.

Yes that is correct

**Comment by jkrogers18** [comment]
Tests are still failing for me even with the latest commits. Logs [here](https://drive.google.com/file/d/12Z08nLiJIOPF58utl2CbV0fhBoNhnT0G/view?usp=sharing)

**Comment by moschetti** [comment]
I'm also getting the same failures as Jamie
2 Failures, and a few other errors. The failures are:
```
ProcessActivityStateControllerTest.shouldUpdateActivityState:184 Status expected:<200> but was:<400>
ProcessActivityStateControllerTest.shouldUpdateActivityStateMultiple:238 Status expected:<200> but was:<400>
```

**Comment by dhanyak-btc** [comment]
@googlebot I consent.

**Comment by jkrogers18** [comment]
Tests still failing after this latest commit. Logs [here](https://drive.google.com/file/d/12_oYiyD6WAuzC56TxE6iREXCTNb0ddtn/view?usp=sharing).

**Comment by dhanyak-btc** [comment]
@jkrogers18 @moschetti We're able to re-produce the build issues earlier and same as been fixed in previous two commits but the fix didn't work when you tested on VM. We're are unable to re-produce the issue as the previous fix solved the problem.

I think the port conflict issue may be due to` server.port=8080` in `application.properties.` Spring Boot Test configured to use the random port and Wiremock configured with 8080. Looks like the Spring Test is using  `server.port=8080` while initializing the server or some process may be already running on 8080 this causes `port already in use` error.

I'm making the code changes to use DEFINED_PORT instead of RANDOM_PORT and run the spring on 54904 and wiremock on 54804 to avoid using default ports. All the tests are successful except `EnrollmentTokenControllerTest `from enrollment module. We'll look into this test failure tomorrow.

Could you please run the tests from this branch for `consent-mgmt-module`, `auth-server`, `participant-manager-datastore`, `response-datastore`, `user-mgmt-module`? Please let us know if the fix works fine for these modules.

@aswinijena100 Please look into enrollment module tests failure tomorrow.

**Comment by moschetti** [comment]
I tried to just cherry-pick the commits here, but didn't fix it. Details in [my cherry-picked PR](https://github.com/moschetti/fdaexample/pull/14/checks). The GitHub checks failed the build for both participant-datastore-enroll-module & participant-user-datastore.

The Cloud Build fails for response-datastore with the same failures and errors as before, but also now participant-datastore-user-mgmt-module (with 15 NoClassDefFound errors across multiple tests) & participant-datastore-enroll-mgmt-module (the failures in EnrollmentTokenControllerTest) also fail.

I'll test again with a clean new setup using the develop-response-server-build-fail-issue-fix branch completely

**Comment by moschetti** [comment]
Still fails building from this branch.
participant-datastore-user-mgmt-module fails with 15 errors:
```
[ERROR] Errors: 
[ERROR]   StudiesControllerTest.addUpdateStudyMetadataSuccess:141->BaseMockIT.verifyAuditEventCall:198->BaseMockIT.verifyAuditEventCall:228 » NoClassDefFound
[ERROR]   UserProfileControllerTest.deactivateAccountSuccess:322->BaseMockIT.verifyAuditEventCall:198->BaseMockIT.verifyAuditEventCall:228 » NoClassDefFound
[ERROR]   UserProfileControllerTest.getUserProfileBadRequest:153->BaseMockIT.verifyAuditEventCall:198->BaseMockIT.verifyAuditEventCall:228 » NoClassDefFound
[ERROR]   UserProfileControllerTest.getUserProfileSuccess:131->BaseMockIT.verifyAuditEventCall:198->BaseMockIT.verifyAuditEventCall:228 » NoClassDefFound
[ERROR]   UserProfileControllerTest.resendConfirmationSuccess:421->BaseMockIT.verifyAuditEventCall:198->BaseMockIT.verifyAuditEventCall:228 » NoClassDefFound
[ERROR]   UserProfileControllerTest.updateUserProfileSuccess:181->BaseMockIT.verifyAuditEventCall:198->BaseMockIT.verifyAuditEventCall:228 » NoClassDefFound
[ERROR]   UserProfileControllerTest.updateUserProfileWithoutSettingsBeanSuccess:221->BaseMockIT.verifyAuditEventCall:198->BaseMockIT.verifyAuditEventCall:228 » NoClassDefFound
[ERROR]   UserRegistrationControllerTest.shouldRegisterUser:219->BaseMockIT.verifyAuditEventCall:198->BaseMockIT.verifyAuditEventCall:228 » NoClassDefFound
[ERROR]   UserRegistrationControllerTest.shouldReturnBadRequestForEmailExists:156->BaseMockIT.verifyAuditEventCall:198->BaseMockIT.verifyAuditEventCall:228 » NoClassDefFound
[ERROR]   UserSupportControllerTest.shouldSendEmailForContactUs:132->BaseMockIT.verifyAuditEventCall:198->BaseMockIT.verifyAuditEventCall:228 » NoClassDefFound
[ERROR]   UserSupportControllerTest.shouldSendFeedbackEmail:89->BaseMockIT.verifyAuditEventCall:198->BaseMockIT.verifyAuditEventCall:228 » NoClassDefFound
[ERROR]   VerifyEmailIdControllerTest.shouldReturnBadRequestForEmailNotExists:149->BaseMockIT.verifyAuditEventCall:198->BaseMockIT.verifyAuditEventCall:228 » NoClassDefFound
[ERROR]   VerifyEmailIdControllerTest.shouldReturnBadRequestForInvalidCode:93->BaseMockIT.verifyAuditEventCall:198->BaseMockIT.verifyAuditEventCall:228 » NoClassDefFound
[ERROR]   VerifyEmailIdControllerTest.shouldReturnBadRequestForInvalidEmailId:122->BaseMockIT.verifyAuditEventCall:198->BaseMockIT.verifyAuditEventCall:228 » NoClassDefFound
[ERROR]   VerifyEmailIdControllerTest.shouldUpdateEmailStatusToVerified:196->BaseMockIT.verifyAuditEventCall:198->BaseMockIT.verifyAuditEventCall:228 » NoClassDefFound
```

response-datastore fails with 2 failures and 15 errors:
```
[ERROR] Failures: 
[ERROR]   ProcessActivityStateControllerTest.shouldUpdateActivityState:184 Status expected:<200> but was:<400>
[ERROR]   ProcessActivityStateControllerTest.shouldUpdateActivityStateMultiple:238 Status expected:<200> but was:<400>
[ERROR] Errors: 
[ERROR]   ProcessActivityResponseControllerTest.shouldDeleteParticipantFromStudy » IllegalState
[ERROR]   ProcessActivityResponseControllerTest.shouldGetActivityResponse » IllegalState
[ERROR]   ProcessActivityResponseControllerTest.shouldReturnBadRequestForEmptyInputsOfProccessActivityResponse » IllegalState
[ERROR]   ProcessActivityResponseControllerTest.shouldReturnBadRequestForEmptyInputsOfWithdraw » IllegalState
[ERROR]   ProcessActivityResponseControllerTest.shouldReturnBadRequestForInvalidParticipant » IllegalState
[ERROR]   ProcessActivityResponseControllerTest.shouldReturnBadRequestsGetActivityResponse » IllegalState
[ERROR]   ProcessActivityResponseControllerTest.shouldSaveProcessActivityResponse » IllegalState
[ERROR]   ProcessActivityResponseControllerTest.shouldUpdateWithdrawStatusParticipantFromStudy » IllegalState
[ERROR]   ProcessActivityStateControllerTest.cleanUp:290 » InvalidDataAccessResourceUsage
[ERROR]   ProcessActivityStateControllerTest.cleanUp:290 » InvalidDataAccessResourceUsage
[ERROR]   ProcessActivityStateControllerTest.shouldGetActivityStateValidParams:60 » ProcessActivityState
[ERROR]   ProcessActivityStateControllerTest.shouldGetEmptyActivityStateParamsNotFound:105 » ProcessActivityState
[ERROR]   ProcessActivityStateControllerTest.shouldGetEmptyActivityStateParamsNotFound:105 » ProcessActivityState
[ERROR]   StudyMetadataControllerTest.testStudyMetadataSavedContent » IllegalState Faile...
[ERROR]   StudyMetadataControllerTest.testStudyMetadataSavedContentInvalidStudyId » IllegalState
```

participant-datastore-enroll-mgmt-module fails with 4 failures and 2 errors:
```
[ERROR] Failures: 
[ERROR]   EnrollmentTokenControllerTest.enrollParticipantSuccessStudyTypeClose:299 Status expected:<200> but was:<403>
[ERROR]   EnrollmentTokenControllerTest.shouldFailEnrollmentForExistingParticipant:433 Status expected:<200> but was:<403>
[ERROR]   EnrollmentTokenControllerTest.shouldNotAllowUserForEnrollment:337 Status expected:<410> but was:<403>
[ERROR]   EnrollmentTokenControllerTest.shouldReturnUnknownTokenForEnrollment:366 Status expected:<400> but was:<403>
[ERROR] Errors: 
[ERROR]   EnrollmentTokenControllerTest.validateEnrollmentForExpiredToken:220 Â» NoSuchElement
[ERROR]   EnrollmentTokenControllerTest.validateEnrollmentTokenSuccess:74 Â» NoSuchElement
```

**Comment by jkrogers18** [comment]
It seems that there must be something different about the environment that Dhanya and Ashwini are using to test these changes and the environments that we are using. Would it be more efficient for the BTC team to align to this environment (fresh GCE VM with Debian 10 - see any of the READMEs), especially since this is what we recommend in the documentation? That way we're not testing fixes across timezones.

**Comment by aswinijena100** [comment]
Closing this PR . Separate PR #2624 raised for this issue Fix

**Pull request closed without merging**
