### PR TITLE
[v2.0.6] [SB] Provision for import/export and replication of studies 

### PR DESCRIPTION
**Pull request by Kantharajut-btc**
Added functionality for
- Export a study from the SB and be able to import into another version-compatible. Please refer #3114 
- Copy a study into a new one within the same Study Builder. Please refer #3321

### CODE REVIEW

**Comment by navya-BTC** [comment]
@googlebot I consent.

**Comment by Kantharajut-btc** [comment]
@googlebot I consent.

**Comment by monica-BTC** [comment]
@googlebot I consent.

**Comment by chiranjibi009** [comment]
@googlebot I consent.

**Comment by madhurya-btc** [comment]
@googlebot I consent.

**Review by moschetti — APPROVED** [review]

**Pull request merged**
