### PR TITLE
Issue #2354 - Removed @DirtiesContext from Tests and Wiremock initialization

### PR DESCRIPTION
**Pull request by dhanyak-btc**
Removed @DirtiesContext from Tests and Wiremock initialization once

### CODE REVIEW

**Comment by dhanyak-btc** [comment]
@googlebot I consent.

**Comment by dhanyak-btc** [comment]
@googlebot I consent.

**Comment by dhanyak-btc** [comment]
@googlebot I consent.

**Comment by chiranjibi009** [comment]
@googlebot I consent

**Comment by dhanyak-btc** [comment]
@moschetti @jkrogers18 We fixed the tests failure, kindly run the tests from this branch `issue-2354-build-issues`. As discussed in today's call we run these tests on Debian OS tomorrow.

**Comment by jkrogers18** [comment]
confirmed that response-datastore and the 3 participant-datastore modules build with successful tests in the GCE VM

**Review by jkrogers18 — APPROVED** [review]

**Pull request merged**
