### PR TITLE
Synch Develop branch with Master branch

### PR DESCRIPTION
**Pull request by aswinijena100**
This PR created to synch develop branch with master by pulling latest review comment fixes that happened directly on release candidate for the PR #3170

### CODE REVIEW

**Comment by aswinijena100** [comment]
@googlebot I consent.

**Comment by dhanyak-btc** [comment]
@googlebot I consent.

**Comment by naveenr-btc** [comment]
@googlebot I consent.

**Comment by firdosebtc1** [comment]
@googlebot I consent.

**Comment by harisboston** [comment]
@googlebot I consent.

**Comment by madhurya-btc** [comment]
@googlebot I consent.

**Comment by mohangmk** [comment]
@googlebot I consent.

**Comment by Madhud5** [comment]
@googlebot I consent.

**Comment by jkrogers18** [comment]
@googlebot I consent

**Review by moschetti — APPROVED** [review]

**Pull request merged**
