### PR TITLE
Android - instruction step rich text support

### PR DESCRIPTION
**Pull request by naveenr-btc**
ResearchStack doesn't support Rich text for instruction, so added customization to support it

### CODE REVIEW

**Comment by moschetti** [comment]
please address Zohreh's comments above

**Comment by bhushanboston** [comment]
@googlebot I consent.

**Comment by bhushanboston** [comment]
> please address Zohreh's comments above

Added test cases in latest commit

**Comment by moschetti** [comment]
please add javadoc comments still too as shown in the commit

**Comment by bhushanboston** [comment]
> please add javadoc comments still too as shown in the commit

Added javadoc comment for instruction step custom class

**Review by moschetti — APPROVED** [review]

**Pull request merged**
