### PR TITLE
Release candidate - 2.0.3

### PR DESCRIPTION
**Pull request by aswinijena100**
Release 2.0.3

•	API documentation using Swagger libraries
•	Provision for database migration using Flyway
•	Minor enhancements 
•	Bug fixes 
•	The full items addressed in this release can be viewed [here](https://github.com/GoogleCloudPlatform/fda-mystudies/milestone/6?closed=1)

### CODE REVIEW

**Comment by aswinijena100** [comment]
@googlebot I consent.

**Comment by pujithr** [comment]
@googlebot I consent.

**Comment by naveenr-btc** [comment]
@googlebot I consent.

**Comment by mohangmk** [comment]
@googlebot I consent

**Comment by harisboston** [comment]
@googlebot I consent.

**Comment by chiranjibi009** [comment]
@googlebot I consent.

**Comment by dhanyak-btc** [comment]
@googlebot I consent.

**Comment by navya-BTC** [comment]
@googlebot I consent.

**Comment by Kantharajut-btc** [comment]
@googlebot I consent.

**Comment by sujatha-btc** [comment]
@googlebot I consent.

**Comment by monica-BTC** [comment]
@googlebot I consent.

**Comment by GovindPrasadBostonTechnologyCorporation** [comment]
@googlebot   i consent.

**Comment by madhurya-btc** [comment]
@googlebot I consent.

**Comment by Madhud5** [comment]
@googlebot i consent.

**Comment by jkrogers18** [comment]
Please add 2.0.3 section to the whats-new readme

**Comment by moschetti** [comment]
> Please add 2.0.3 section to the whats-new readme

I am actually doing that right now.

**Comment by moschetti** [comment]
Please create a new file /documentation/API/README.md that explains how to use the Swagger API docs.

**Comment by moschetti** [comment]
swagger readme merging to develop branch in #3337. Once that's done, merge #3336 which includes the updated whats-new.

**Comment by aswinijena100** [comment]
> swagger readme merging to develop branch in #3337. Once that's done, merge #3336 which includes the updated whats-new.

@moschetti PR #3337 and PR #3336  both merged with release candidate now. Please review and approve the PR

**Review by moschetti — APPROVED** [review]

**Pull request merged**
