### PR TITLE
[Participant Datastore] Sql Dump fail issue fix

### PR DESCRIPTION
**Pull request by aswinijena100**
[Participant Datastore] SQL Dump fail issue #2534  fix

### CODE REVIEW

**Review by moschetti — APPROVED** [review]

**Comment by jkrogers18** [comment]
Do these latest commits fixed the issue? I want to confirm since I'd prefer not to merge things into develop that are still broken.

**Comment by aswinijena100** [comment]
> Do these latest commits fix the issue? I want to confirm since I'd prefer not to merge things into develop that are still broken.
@jkrogers18 I reproduced the issue by uploading the database dump. This fix resolved the issue  also when verifying the script with with our dev environment , found few matches in the newly added fields. I have included those fields also in this PR.

**Comment by jkrogers18** [comment]
The latest sql dump file in this branch appears to work for me. Will wait for @moschetti to confirm and mark as approved.

**Comment by moschetti** [comment]
confirmed this works now.
update the branch and merge

**Pull request merged**
