### PR TITLE
update whats new for 2.0.6

### PR DESCRIPTION
**Pull request by moschetti**

### CODE REVIEW

**Comment by moschetti** [comment]
@mohangmk could you please also update this file when you do the documentation updates to include a link to the new docs on import/export in the first bullet point?

**Comment by mohangmk** [comment]
@moschetti 
As discussed in the last week call, I have created a document with few steps for existing customers to implement import &export study feature. Please review it and add the same to deployment/readme doc.
https://docs.google.com/document/d/1Ej29nRWz4YUZtzuTfIQikPUPfO5N9XvcS5YMsVrYneQ/edit?usp=sharing

**Comment by moschetti** [comment]
Added documentation in #3809 and sent to @mohangmk for review
Will add another commit to this PR which includes updated links.

**Comment by moschetti** [comment]
@mohangmk #3809 is merged, please review the last update here which includes the link to the Readme section added in that PR.

**Review by mohangmk — APPROVED** [review]
looks perfect

**Pull request merged**
