### PR TITLE
Participant manager webapp #2026 issue fix

### PR DESCRIPTION
**Pull request by prakashm181**
Participant manager webapp #2026 issue fix

### CODE REVIEW

**Comment by jkrogers18** [comment]
I believe PRs should be getting merged into the develop branch. We'll only merge releases into master.

**Comment by prakashm181** [comment]
#2026 issue has been fixed kindly approve this .

**Comment by Madhud5** [comment]
@googlebot I consent

**Review by moschetti — APPROVED** [review]

**Comment by prakashm181** [comment]
We have changed base branch from master to develop kindly approve

**Review by moschetti — APPROVED** [review]

**Pull request merged**
