### PR TITLE
Release candidate - 2.0.5

### PR DESCRIPTION
**Pull request by aswinijena100**
Release 2.0.5
- Changes to Cloud Storage permissions for study resources in new deployments. For upgrading existing deployments, follow [these steps](/deployment/README.md#study-resources-in-cloud-storage-205-upgrade).
-  Added support for additional email services
- Bug fixes and UI refinements
-  Additional code improvements and minor enhancements
-  The full list of bugs and features addressed in this release can be viewed [here](https://github.com/GoogleCloudPlatform/fda-mystudies/milestone/8?closed=1)

### CODE REVIEW

**Comment by aswinijena100** [comment]
@googlebot I consent.

**Comment by harisboston** [comment]
@googlebot I consent.

**Comment by monica-BTC** [comment]
@googlebot I consent.

**Comment by madhurya-btc** [comment]
@googlebot I consent.

**Comment by GovindPrasadBostonTechnologyCorporation** [comment]
@googlebot I consent.

**Comment by Madhud5** [comment]
@googlebot I consent

**Comment by pujithr** [comment]
@googlebot I consent.

**Comment by Madhud5** [comment]
@googlebot I consent

**Comment by Madhud5** [comment]
@googlebot I consent

**Comment by firdosebtc1** [comment]
@googlebot I consent.

**Comment by naveenr-btc** [comment]
@googlebot I consent.

**Comment by Kantharajut-btc** [comment]
@googlebot I consent.

**Comment by navya-BTC** [comment]
@googlebot I consent.

**Comment by rohitn-boston** [comment]
@googlebot I consent.

**Comment by mohangmk** [comment]
@googlebot I consent

**Comment by mohangmk** [comment]
@googlebot I consent.

**Comment by chiranjibi009** [comment]
@googlebot I consent.

**Review by moschetti — APPROVED** [review]

**Pull request merged**
